# Generated by Django 3.2.9 on 2021-11-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=255)),
                ('action_name', models.CharField(max_length=255)),
                ('action_category', models.CharField(max_length=255)),
                ('action_timestamp', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('eye_data', models.JSONField()),
            ],
        ),
    ]
